// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCox6Hm7imtxV35uKXHEm0yVlH7cpptKks',
    appId: '1:845043759805:web:03df43e8bb1a1a528595d4',
    messagingSenderId: '845043759805',
    projectId: 'balanced-meal-26htnc',
    authDomain: 'balanced-meal-26htnc.firebaseapp.com',
    storageBucket: 'balanced-meal-26htnc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASx0d5caFYoOpjpJeGGEacUUg8-frNNlw',
    appId: '1:845043759805:android:552e26a07cdb4ae38595d4',
    messagingSenderId: '845043759805',
    projectId: 'balanced-meal-26htnc',
    storageBucket: 'balanced-meal-26htnc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeC_4A7oQth-AtX7-kTsnfsQ779uKPBhM',
    appId: '1:845043759805:ios:b36a9420e0769f058595d4',
    messagingSenderId: '845043759805',
    projectId: 'balanced-meal-26htnc',
    storageBucket: 'balanced-meal-26htnc.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeC_4A7oQth-AtX7-kTsnfsQ779uKPBhM',
    appId: '1:845043759805:ios:b36a9420e0769f058595d4',
    messagingSenderId: '845043759805',
    projectId: 'balanced-meal-26htnc',
    storageBucket: 'balanced-meal-26htnc.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCox6Hm7imtxV35uKXHEm0yVlH7cpptKks',
    appId: '1:845043759805:web:74d7e5ee82deece58595d4',
    messagingSenderId: '845043759805',
    projectId: 'balanced-meal-26htnc',
    authDomain: 'balanced-meal-26htnc.firebaseapp.com',
    storageBucket: 'balanced-meal-26htnc.firebasestorage.app',
  );
}
